walkforward:
  train_years: 5
  test_years: 3
  step_years: 1
grid:
  weights.w_1m:
  - 0.1
  - 0.2
  weights.w_6m:
  - 0.4
  weights.w_12m:
  - 0.4
  - 0.5
  filters.regime_ma_days:
  - 150
  - 200
  - 250
  leverage.thr_3x:
  - 0.85
  - 0.9
  - 0.95
  - 1.0
  leverage.thr_2x:
  - 1.1
  - 1.2
  - 1.3
  selection.top_n:
  - 1
  - 2
ranking:
  primary: median_calmar
  constraints:
    max_mdd: -0.8
